_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.54610294  0.9809799  -0.6304918  ...  0.          0.
           0.        ]
         [-0.07934564 -0.72358334  0.33102053 ...  0.          0.
           0.        ]
         [ 0.01526867 -0.29103532 -0.26817462 ...  0.          0.
           0.        ]
         [-0.46687204  0.04464865  0.5675756  ...  0.          0.
           0.        ]]
_last_original_obs:
    value: |-
        [[ 1.39976702e+00  1.00780650e+00 -7.57591543e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.39401049e+00  9.92341368e-01 -2.11282788e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.39488131e+00  9.96265781e-01 -5.51731439e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.39044377e+00  9.99311368e-01 -7.68777668e-04 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x30dcd8e90>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 10000000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x169f9ec10>
_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/src/train_humanoid_ppo.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x30d226980>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x169f9ec10>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.995
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x15906d940>
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (348,), float64)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=348, out_features=512, bias=True)
              (1): Tanh()
              (2): Linear(in_features=512, out_features=512, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=348, out_features=512, bias=True)
              (1): Tanh()
              (2): Linear(in_features=512, out_features=512, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=512, out_features=17, bias=True)
          (value_net): Linear(in_features=512, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [{''pi'': [512, 512], ''vf'': [512, 512]}]}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x16ae79950>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1748029351466312000
target_kl:
    value: None
tensorboard_log:
    value: ./runs/ppo_humanoid/20250523-124229
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
