_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.26028427 -0.4087816   0.76875895 ...  0.          0.
           0.        ]
         [ 0.1250613   0.6034067  -0.21472618 ...  0.          0.
           0.        ]
         [-0.7620067   0.6825921   0.69627136 ...  0.          0.
           0.        ]
         [ 0.39119038 -0.86659336 -1.2502726  ...  0.          0.
           0.        ]]
_last_original_obs:
    value: |-
        [[ 1.40605043e+00  9.98717001e-01  9.45029922e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.40474417e+00  1.00826904e+00  8.72241801e-04 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.39617502e+00  1.00901632e+00  8.81805511e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]
         [ 1.40731500e+00  9.94396622e-01 -8.15989985e-03 ...  0.00000000e+00
           0.00000000e+00  0.00000000e+00]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x166053890>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 10000000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x1502dee50>
_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/src/train_humanoid_ppo.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x167b27420>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x1502dee50>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x146bc3600>
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (348,), float64)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=348, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=348, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=17, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x1502f5810>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1748926487533590000
target_kl:
    value: None
tensorboard_log:
    value: ./runs/ppo_humanoid/20250602-215445
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
